language: node_js
node_js:
  - "node"
warnings_are_errors: false

branches:
  only:
    - master
    - Cucho


before_install: 
  - cd Frontend/

install:
  - npm install
script:
  - npm run build

#Comentario para probar branch

deploy:
  provider: firebase
  skip_cleanup: true
  token: $FIRE_TOKEN