language: node_js
node_js:
  - "node"
warnings_are_errors: false
before_install: 
  - cd Frontend/

install:
  - npm install
script:
  - npm run build

notificatios
deploy:
  provider: firebase
  skip_cleanup: true
  token: 1//05NXJazybgtlkCgYIARAAGAUSNgF-L9Iriv9qGIxnlwMDQ7LccmHXDX_PJkbqDxm9dmn3QdVTaV8HoNMTidWfI2OkFGir4HI4xg