languaje: python
python:
  - "3.6"

env:
  - DJANGO=3.0

before_install:
  - cd Backend/
install:
  - "pip3 install -r requirements.txt"

before_script:
  - cd Backend/
  - cd django-back/

script: 
  - python manage.py test

deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  api-key: ceb5ac04-5ab8-4ccf-b813-f22b4865abfb
  app: energycorp
  on: 
    repo: esneidermanzano/energyCorp/