language: node_js
node_js:
  - "node"
warnings_are_errors: false
before_install: 
  - cd Frontend/

install:
  - npm install
script:
  - npm run build

after_success:
  - ./travis_merge.sh
#Comentario para probar branch
notificatios
deploy:
  provider: firebase
  skip_cleanup: true
  token: $FIRE_TOKEN