language: node_js
node_js:
  - "node"
warnings_are_errors: false
install:
  - npm install
script:
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token: 1//05NXJazybgtlkCgYIARAAGAUSNgF-L9Iriv9qGIxnlwMDQ7LccmHXDX_PJkbqDxm9dmn3QdVTaV8HoNMTidWfI2OkFGir4HI4xg